export type ElementCategory =
  | "tables"
  | "seating"
  | "fixtures"
  | "walls"
  | "decor"

export type ElementShape =
  | "rect"
  | "circle"
  | "ellipse"
  | "l-shape"

export interface FloorplanElementTemplate {
  id: string
  category: ElementCategory
  label: string
  icon: string
  defaultWidth: number
  defaultHeight: number
  shape: ElementShape
  color: string
  minWidth?: number
  minHeight?: number
  maxWidth?: number
  maxHeight?: number
  seats?: number
}

export interface PlacedElement {
  id: string
  templateId: string
  x: number
  y: number
  width: number
  height: number
  rotation: number
  label: string
  shape: ElementShape
  color: string
  locked: boolean
  opacity: number
  category: ElementCategory
  seats?: number
  customLabel?: string
}

export interface CanvasState {
  zoom: number
  panX: number
  panY: number
  gridSize: number
  showGrid: boolean
  snapToGrid: boolean
}

export interface HistoryEntry {
  elements: PlacedElement[]
  timestamp: number
}

export const ELEMENT_TEMPLATES: FloorplanElementTemplate[] = [
  // ── Tables ──────────────────────────────────────────────────────
  {
    id: "table-round-2",
    category: "tables",
    label: "Round 2-Top",
    icon: "circle",
    defaultWidth: 60,
    defaultHeight: 60,
    shape: "circle",
    color: "hsl(185, 85%, 45%)",
    seats: 2,
  },
  {
    id: "table-round-4",
    category: "tables",
    label: "Round 4-Top",
    icon: "circle",
    defaultWidth: 80,
    defaultHeight: 80,
    shape: "circle",
    color: "hsl(185, 85%, 45%)",
    seats: 4,
  },
  {
    id: "table-round-6",
    category: "tables",
    label: "Round 6-Top",
    icon: "circle",
    defaultWidth: 100,
    defaultHeight: 100,
    shape: "circle",
    color: "hsl(185, 85%, 45%)",
    seats: 6,
  },
  {
    id: "table-round-8",
    category: "tables",
    label: "Round 8-Top",
    icon: "circle",
    defaultWidth: 120,
    defaultHeight: 120,
    shape: "circle",
    color: "hsl(185, 80%, 42%)",
    seats: 8,
  },
  {
    id: "table-square-2",
    category: "tables",
    label: "Square 2-Top",
    icon: "square",
    defaultWidth: 60,
    defaultHeight: 60,
    shape: "rect",
    color: "hsl(185, 85%, 45%)",
    seats: 2,
  },
  {
    id: "table-square-4",
    category: "tables",
    label: "Square 4-Top",
    icon: "square",
    defaultWidth: 80,
    defaultHeight: 80,
    shape: "rect",
    color: "hsl(185, 85%, 45%)",
    seats: 4,
  },
  {
    id: "table-rect-6",
    category: "tables",
    label: "Rect 6-Top",
    icon: "rectangle-horizontal",
    defaultWidth: 140,
    defaultHeight: 70,
    shape: "rect",
    color: "hsl(185, 85%, 45%)",
    seats: 6,
  },
  {
    id: "table-rect-8",
    category: "tables",
    label: "Rect 8-Top",
    icon: "rectangle-horizontal",
    defaultWidth: 180,
    defaultHeight: 70,
    shape: "rect",
    color: "hsl(185, 85%, 45%)",
    seats: 8,
  },
  {
    id: "table-long-10",
    category: "tables",
    label: "Banquet 10-Top",
    icon: "rectangle-horizontal",
    defaultWidth: 240,
    defaultHeight: 80,
    shape: "rect",
    color: "hsl(185, 65%, 40%)",
    seats: 10,
  },
  {
    id: "table-long-12",
    category: "tables",
    label: "Banquet 12-Top",
    icon: "rectangle-horizontal",
    defaultWidth: 280,
    defaultHeight: 80,
    shape: "rect",
    color: "hsl(185, 65%, 40%)",
    seats: 12,
  },
  {
    id: "table-cocktail",
    category: "tables",
    label: "Cocktail Table",
    icon: "circle",
    defaultWidth: 40,
    defaultHeight: 40,
    shape: "circle",
    color: "hsl(185, 70%, 50%)",
    seats: 0,
  },
  {
    id: "table-highboy",
    category: "tables",
    label: "Highboy Table",
    icon: "circle",
    defaultWidth: 50,
    defaultHeight: 50,
    shape: "circle",
    color: "hsl(185, 75%, 48%)",
    seats: 4,
  },
  {
    id: "table-oval-6",
    category: "tables",
    label: "Oval 6-Top",
    icon: "circle",
    defaultWidth: 140,
    defaultHeight: 80,
    shape: "ellipse",
    color: "hsl(185, 80%, 43%)",
    seats: 6,
  },
  {
    id: "table-counter",
    category: "tables",
    label: "Counter Table",
    icon: "rectangle-horizontal",
    defaultWidth: 120,
    defaultHeight: 40,
    shape: "rect",
    color: "hsl(185, 60%, 38%)",
    seats: 4,
  },
  {
    id: "table-coffee",
    category: "tables",
    label: "Coffee Table",
    icon: "rectangle-horizontal",
    defaultWidth: 80,
    defaultHeight: 50,
    shape: "rect",
    color: "hsl(30, 40%, 40%)",
    seats: 0,
  },
  {
    id: "table-kids",
    category: "tables",
    label: "Kids Table",
    icon: "square",
    defaultWidth: 60,
    defaultHeight: 60,
    shape: "rect",
    color: "hsl(185, 90%, 55%)",
    seats: 4,
  },

  // ── Seating ─────────────────────────────────────────────────────
  {
    id: "chair",
    category: "seating",
    label: "Chair",
    icon: "armchair",
    defaultWidth: 30,
    defaultHeight: 30,
    shape: "rect",
    color: "hsl(220, 15%, 35%)",
  },
  {
    id: "chair-dining",
    category: "seating",
    label: "Dining Chair",
    icon: "armchair",
    defaultWidth: 35,
    defaultHeight: 35,
    shape: "rect",
    color: "hsl(220, 18%, 38%)",
  },
  {
    id: "chair-accent",
    category: "seating",
    label: "Accent Chair",
    icon: "armchair",
    defaultWidth: 50,
    defaultHeight: 50,
    shape: "rect",
    color: "hsl(38, 55%, 45%)",
  },
  {
    id: "chair-lounge",
    category: "seating",
    label: "Lounge Chair",
    icon: "armchair",
    defaultWidth: 60,
    defaultHeight: 55,
    shape: "rect",
    color: "hsl(220, 20%, 32%)",
  },
  {
    id: "booth-2",
    category: "seating",
    label: "Booth (2-seat)",
    icon: "sofa",
    defaultWidth: 100,
    defaultHeight: 50,
    shape: "rect",
    color: "hsl(38, 70%, 45%)",
    seats: 2,
  },
  {
    id: "booth-4",
    category: "seating",
    label: "Booth (4-seat)",
    icon: "sofa",
    defaultWidth: 140,
    defaultHeight: 50,
    shape: "rect",
    color: "hsl(38, 70%, 45%)",
    seats: 4,
  },
  {
    id: "booth-6",
    category: "seating",
    label: "Booth (6-seat)",
    icon: "sofa",
    defaultWidth: 180,
    defaultHeight: 55,
    shape: "rect",
    color: "hsl(38, 65%, 42%)",
    seats: 6,
  },
  {
    id: "booth-corner",
    category: "seating",
    label: "Corner Booth",
    icon: "sofa",
    defaultWidth: 120,
    defaultHeight: 120,
    shape: "rect",
    color: "hsl(38, 60%, 40%)",
    seats: 6,
  },
  {
    id: "bar-stool",
    category: "seating",
    label: "Bar Stool",
    icon: "circle",
    defaultWidth: 28,
    defaultHeight: 28,
    shape: "circle",
    color: "hsl(220, 15%, 30%)",
  },
  {
    id: "bench",
    category: "seating",
    label: "Bench",
    icon: "rectangle-horizontal",
    defaultWidth: 120,
    defaultHeight: 35,
    shape: "rect",
    color: "hsl(38, 50%, 40%)",
  },
  {
    id: "bench-long",
    category: "seating",
    label: "Long Bench",
    icon: "rectangle-horizontal",
    defaultWidth: 180,
    defaultHeight: 35,
    shape: "rect",
    color: "hsl(38, 50%, 38%)",
  },
  {
    id: "sofa-2",
    category: "seating",
    label: "Loveseat",
    icon: "sofa",
    defaultWidth: 100,
    defaultHeight: 55,
    shape: "rect",
    color: "hsl(220, 18%, 32%)",
    seats: 2,
  },
  {
    id: "sofa-3",
    category: "seating",
    label: "Sofa (3-seat)",
    icon: "sofa",
    defaultWidth: 150,
    defaultHeight: 55,
    shape: "rect",
    color: "hsl(220, 18%, 32%)",
    seats: 3,
  },
  {
    id: "sofa-sectional",
    category: "seating",
    label: "Sectional Sofa",
    icon: "sofa",
    defaultWidth: 160,
    defaultHeight: 120,
    shape: "rect",
    color: "hsl(220, 20%, 30%)",
    seats: 6,
  },
  {
    id: "ottoman",
    category: "seating",
    label: "Ottoman",
    icon: "square",
    defaultWidth: 45,
    defaultHeight: 45,
    shape: "rect",
    color: "hsl(30, 35%, 38%)",
  },
  {
    id: "waiting-chair",
    category: "seating",
    label: "Waiting Chair",
    icon: "armchair",
    defaultWidth: 40,
    defaultHeight: 40,
    shape: "rect",
    color: "hsl(220, 12%, 33%)",
  },

  // ── Fixtures ────────────────────────────────────────────────────
  {
    id: "bar-counter",
    category: "fixtures",
    label: "Bar Counter",
    icon: "rectangle-horizontal",
    defaultWidth: 200,
    defaultHeight: 50,
    shape: "rect",
    color: "hsl(30, 50%, 35%)",
    seats: 6,
  },
  {
    id: "bar-corner",
    category: "fixtures",
    label: "L-Bar Counter",
    icon: "rectangle-horizontal",
    defaultWidth: 160,
    defaultHeight: 120,
    shape: "rect",
    color: "hsl(30, 50%, 33%)",
    seats: 8,
  },
  {
    id: "bar-corner-left",
    category: "fixtures",
    label: "L-Bar Left",
    icon: "rectangle-horizontal",
    defaultWidth: 160,
    defaultHeight: 120,
    shape: "rect",
    color: "hsl(30, 50%, 33%)",
    seats: 8,
  },
  {
    id: "bar-curved",
    category: "fixtures",
    label: "Curved Bar",
    icon: "circle",
    defaultWidth: 180,
    defaultHeight: 100,
    shape: "rect",
    color: "hsl(30, 48%, 30%)",
    seats: 6,
  },
  {
    id: "host-stand",
    category: "fixtures",
    label: "Host Stand",
    icon: "monitor",
    defaultWidth: 50,
    defaultHeight: 40,
    shape: "rect",
    color: "hsl(220, 15%, 28%)",
  },
  {
    id: "kitchen-window",
    category: "fixtures",
    label: "Kitchen Window",
    icon: "panel-top",
    defaultWidth: 160,
    defaultHeight: 30,
    shape: "rect",
    color: "hsl(0, 40%, 40%)",
  },
  {
    id: "kitchen-area",
    category: "fixtures",
    label: "Kitchen Area",
    icon: "cooking-pot",
    defaultWidth: 200,
    defaultHeight: 150,
    shape: "rect",
    color: "hsl(220, 12%, 18%)",
  },
  {
    id: "service-station",
    category: "fixtures",
    label: "Service Station",
    icon: "coffee",
    defaultWidth: 60,
    defaultHeight: 60,
    shape: "rect",
    color: "hsl(220, 15%, 25%)",
  },
  {
    id: "restroom",
    category: "fixtures",
    label: "Restroom",
    icon: "door-open",
    defaultWidth: 80,
    defaultHeight: 80,
    shape: "rect",
    color: "hsl(220, 15%, 20%)",
  },
  {
    id: "cash-register",
    category: "fixtures",
    label: "Cash Register",
    icon: "monitor",
    defaultWidth: 50,
    defaultHeight: 40,
    shape: "rect",
    color: "hsl(220, 15%, 28%)",
  },
  {
    id: "sink",
    category: "fixtures",
    label: "Sink",
    icon: "droplets",
    defaultWidth: 45,
    defaultHeight: 35,
    shape: "rect",
    color: "hsl(210, 20%, 30%)",
  },
  {
    id: "refrigerator",
    category: "fixtures",
    label: "Refrigerator",
    icon: "square",
    defaultWidth: 55,
    defaultHeight: 60,
    shape: "rect",
    color: "hsl(210, 10%, 40%)",
  },
  {
    id: "oven",
    category: "fixtures",
    label: "Oven / Range",
    icon: "cooking-pot",
    defaultWidth: 60,
    defaultHeight: 55,
    shape: "rect",
    color: "hsl(0, 25%, 30%)",
  },
  {
    id: "dishwasher",
    category: "fixtures",
    label: "Dishwasher",
    icon: "square",
    defaultWidth: 50,
    defaultHeight: 50,
    shape: "rect",
    color: "hsl(210, 10%, 35%)",
  },
  {
    id: "wine-rack",
    category: "fixtures",
    label: "Wine Rack",
    icon: "wine",
    defaultWidth: 80,
    defaultHeight: 30,
    shape: "rect",
    color: "hsl(350, 40%, 30%)",
  },
  {
    id: "buffet-station",
    category: "fixtures",
    label: "Buffet Station",
    icon: "rectangle-horizontal",
    defaultWidth: 180,
    defaultHeight: 60,
    shape: "rect",
    color: "hsl(30, 40%, 30%)",
  },
  {
    id: "salad-bar",
    category: "fixtures",
    label: "Salad Bar",
    icon: "rectangle-horizontal",
    defaultWidth: 160,
    defaultHeight: 50,
    shape: "rect",
    color: "hsl(140, 30%, 30%)",
  },
  {
    id: "display-case",
    category: "fixtures",
    label: "Display Case",
    icon: "panel-top",
    defaultWidth: 120,
    defaultHeight: 45,
    shape: "rect",
    color: "hsl(200, 15%, 35%)",
  },
  {
    id: "stage",
    category: "fixtures",
    label: "Stage / Platform",
    icon: "rectangle-horizontal",
    defaultWidth: 200,
    defaultHeight: 120,
    shape: "rect",
    color: "hsl(270, 20%, 25%)",
  },
  {
    id: "dj-booth",
    category: "fixtures",
    label: "DJ Booth",
    icon: "music",
    defaultWidth: 80,
    defaultHeight: 60,
    shape: "rect",
    color: "hsl(270, 30%, 30%)",
  },
  {
    id: "coat-check",
    category: "fixtures",
    label: "Coat Check",
    icon: "shirt",
    defaultWidth: 70,
    defaultHeight: 40,
    shape: "rect",
    color: "hsl(220, 12%, 28%)",
  },
  {
    id: "elevator",
    category: "fixtures",
    label: "Elevator",
    icon: "square",
    defaultWidth: 70,
    defaultHeight: 70,
    shape: "rect",
    color: "hsl(220, 10%, 22%)",
  },

  // ── Walls & Dividers ───────────────────────────────────────────
  {
    id: "wall-h",
    category: "walls",
    label: "Wall (Horiz.)",
    icon: "minus",
    defaultWidth: 200,
    defaultHeight: 12,
    shape: "rect",
    color: "hsl(220, 15%, 22%)",
  },
  {
    id: "wall-v",
    category: "walls",
    label: "Wall (Vert.)",
    icon: "minus",
    defaultWidth: 12,
    defaultHeight: 200,
    shape: "rect",
    color: "hsl(220, 15%, 22%)",
  },
  {
    id: "wall-short-h",
    category: "walls",
    label: "Short Wall (H)",
    icon: "minus",
    defaultWidth: 100,
    defaultHeight: 12,
    shape: "rect",
    color: "hsl(220, 15%, 22%)",
  },
  {
    id: "wall-short-v",
    category: "walls",
    label: "Short Wall (V)",
    icon: "minus",
    defaultWidth: 12,
    defaultHeight: 100,
    shape: "rect",
    color: "hsl(220, 15%, 22%)",
  },
  {
    id: "partition",
    category: "walls",
    label: "Partition",
    icon: "rectangle-horizontal",
    defaultWidth: 120,
    defaultHeight: 8,
    shape: "rect",
    color: "hsl(220, 10%, 30%)",
  },
  {
    id: "half-wall",
    category: "walls",
    label: "Half Wall",
    icon: "rectangle-horizontal",
    defaultWidth: 100,
    defaultHeight: 16,
    shape: "rect",
    color: "hsl(220, 12%, 26%)",
  },
  {
    id: "glass-partition",
    category: "walls",
    label: "Glass Partition",
    icon: "rectangle-horizontal",
    defaultWidth: 120,
    defaultHeight: 6,
    shape: "rect",
    color: "hsl(200, 30%, 45%)",
  },
  {
    id: "column",
    category: "walls",
    label: "Column",
    icon: "circle",
    defaultWidth: 24,
    defaultHeight: 24,
    shape: "circle",
    color: "hsl(220, 15%, 25%)",
  },
  {
    id: "column-square",
    category: "walls",
    label: "Square Column",
    icon: "square",
    defaultWidth: 24,
    defaultHeight: 24,
    shape: "rect",
    color: "hsl(220, 15%, 25%)",
  },
  {
    id: "railing",
    category: "walls",
    label: "Railing",
    icon: "minus",
    defaultWidth: 150,
    defaultHeight: 5,
    shape: "rect",
    color: "hsl(220, 12%, 35%)",
  },
  {
    id: "curtain",
    category: "walls",
    label: "Curtain Divider",
    icon: "minus",
    defaultWidth: 140,
    defaultHeight: 4,
    shape: "rect",
    color: "hsl(350, 30%, 35%)",
  },
  {
    id: "doorway",
    category: "walls",
    label: "Doorway",
    icon: "door-open",
    defaultWidth: 50,
    defaultHeight: 12,
    shape: "rect",
    color: "hsl(30, 40%, 35%)",
  },
  {
    id: "arch",
    category: "walls",
    label: "Archway",
    icon: "door-open",
    defaultWidth: 60,
    defaultHeight: 14,
    shape: "rect",
    color: "hsl(30, 35%, 30%)",
  },
  {
    id: "stairs",
    category: "walls",
    label: "Staircase",
    icon: "rectangle-horizontal",
    defaultWidth: 80,
    defaultHeight: 160,
    shape: "rect",
    color: "hsl(220, 12%, 20%)",
  },
  {
    id: "window-wall",
    category: "walls",
    label: "Window Wall",
    icon: "panel-top",
    defaultWidth: 180,
    defaultHeight: 10,
    shape: "rect",
    color: "hsl(200, 40%, 50%)",
  },

  // ── Decor ───────────────────────────────────────────────────────
  {
    id: "plant-large",
    category: "decor",
    label: "Large Plant",
    icon: "tree-palm",
    defaultWidth: 45,
    defaultHeight: 45,
    shape: "circle",
    color: "hsl(140, 50%, 35%)",
  },
  {
    id: "plant-small",
    category: "decor",
    label: "Small Plant",
    icon: "flower-2",
    defaultWidth: 28,
    defaultHeight: 28,
    shape: "circle",
    color: "hsl(140, 45%, 40%)",
  },
  {
    id: "tree-indoor",
    category: "decor",
    label: "Indoor Tree",
    icon: "tree-palm",
    defaultWidth: 55,
    defaultHeight: 55,
    shape: "circle",
    color: "hsl(140, 45%, 30%)",
  },
  {
    id: "planter-box",
    category: "decor",
    label: "Planter Box",
    icon: "flower-2",
    defaultWidth: 100,
    defaultHeight: 30,
    shape: "rect",
    color: "hsl(140, 40%, 32%)",
  },
  {
    id: "rug",
    category: "decor",
    label: "Area Rug",
    icon: "square",
    defaultWidth: 160,
    defaultHeight: 100,
    shape: "rect",
    color: "hsl(30, 30%, 25%)",
  },
  {
    id: "rug-round",
    category: "decor",
    label: "Round Rug",
    icon: "circle",
    defaultWidth: 120,
    defaultHeight: 120,
    shape: "circle",
    color: "hsl(30, 28%, 28%)",
  },
  {
    id: "rug-runner",
    category: "decor",
    label: "Runner Rug",
    icon: "rectangle-horizontal",
    defaultWidth: 200,
    defaultHeight: 40,
    shape: "rect",
    color: "hsl(30, 25%, 23%)",
  },
  {
    id: "fireplace",
    category: "decor",
    label: "Fireplace",
    icon: "flame",
    defaultWidth: 80,
    defaultHeight: 30,
    shape: "rect",
    color: "hsl(15, 60%, 35%)",
  },
  {
    id: "fountain",
    category: "decor",
    label: "Fountain",
    icon: "droplets",
    defaultWidth: 70,
    defaultHeight: 70,
    shape: "circle",
    color: "hsl(200, 60%, 40%)",
  },
  {
    id: "statue",
    category: "decor",
    label: "Statue / Art",
    icon: "gem",
    defaultWidth: 35,
    defaultHeight: 35,
    shape: "circle",
    color: "hsl(45, 30%, 45%)",
  },
  {
    id: "lamp-floor",
    category: "decor",
    label: "Floor Lamp",
    icon: "lamp",
    defaultWidth: 25,
    defaultHeight: 25,
    shape: "circle",
    color: "hsl(45, 60%, 50%)",
  },
  {
    id: "chandelier",
    category: "decor",
    label: "Chandelier",
    icon: "lamp",
    defaultWidth: 60,
    defaultHeight: 60,
    shape: "circle",
    color: "hsl(45, 50%, 55%)",
  },
  {
    id: "mirror",
    category: "decor",
    label: "Wall Mirror",
    icon: "panel-top",
    defaultWidth: 80,
    defaultHeight: 8,
    shape: "rect",
    color: "hsl(200, 25%, 55%)",
  },
  {
    id: "bookshelf",
    category: "decor",
    label: "Bookshelf",
    icon: "rectangle-horizontal",
    defaultWidth: 100,
    defaultHeight: 30,
    shape: "rect",
    color: "hsl(25, 45%, 30%)",
  },
  {
    id: "aquarium",
    category: "decor",
    label: "Aquarium",
    icon: "fish",
    defaultWidth: 100,
    defaultHeight: 40,
    shape: "rect",
    color: "hsl(200, 70%, 40%)",
  },
  {
    id: "candles",
    category: "decor",
    label: "Candle Set",
    icon: "flame",
    defaultWidth: 20,
    defaultHeight: 20,
    shape: "circle",
    color: "hsl(38, 80%, 55%)",
  },
  {
    id: "umbrella",
    category: "decor",
    label: "Patio Umbrella",
    icon: "umbrella",
    defaultWidth: 80,
    defaultHeight: 80,
    shape: "circle",
    color: "hsl(0, 50%, 45%)",
  },
  {
    id: "tv-screen",
    category: "decor",
    label: "TV / Screen",
    icon: "monitor",
    defaultWidth: 90,
    defaultHeight: 10,
    shape: "rect",
    color: "hsl(220, 30%, 20%)",
  },
]

export const CATEGORY_INFO: Record<
  ElementCategory,
  { label: string; icon: string }
> = {
  tables: { label: "Tables", icon: "grid-2x2" },
  seating: { label: "Seating", icon: "armchair" },
  fixtures: { label: "Fixtures", icon: "wrench" },
  walls: { label: "Walls", icon: "square" },
  decor: { label: "Decor", icon: "flower-2" },
}
